# This file contains values from Cookiecutter

default_context:
  project_name: "nafig"
  project_description: "Package for creating figures with NA data distribution"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "VladimirShitov"
  email: "vladimirshitov98@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
